name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  job-one:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      name: testing ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ispcentos.hubo.ru
        username: win-admin
        key: ${{secrets.HUBO_SSH}}
        port: 17222
        script: |
          cd forecast-analyser
          git pull origin master
          git status